### ISSUE TITLE
Doesn't compile

### ISSUE THREAD

**Issue by geoidesic** [jasonsturges/babylonjs-sveltekit#3]
```
failed to load config from /Users/noeldacosta/code/Babylon-svelte/vite.config.ts
error when starting dev server:
file:///Users/noeldacosta/code/Babylon-svelte/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:6
import { isCSSRequest } from 'vite';
         ^^^^^^^^^^^^
SyntaxError: The requested module 'vite' does not provide an export named 'isCSSRequest'
```
And using old version of svelte & svelte-kit

**Comment by jasonsturges** [comment]
@geoidesic Hi, this is pretty old demo that was never updated to SvelteKit - something I had intended eventually in #1.

While it works in its current form, you'd need a proper update to get to the latest SvelteKit.

Let me remind myself of the level of effort here.

**Comment by jasonsturges** [comment]
@geoidesic Actually, I did upgrade this to SvelteKit but maybe something else is new in this ecosystem.

After upgrading packages, it still works with current versions.

You must be bringing something in for this css request issue, as I can't replicate it with this repository in isolation.

**Comment by geoidesic** [comment]
Hi @jasonsturges I literally created a new repo using this one as a template, checked it out, ran `yarn` (from node 16 LTS) and got the error when I ran `yarn dev`.

However, since your update last night, I tried it again from scratch and it is working now. Thanks!
