### ISSUE TITLE
Why is this file .js not .ts?

### ISSUE THREAD

**Issue by geoidesic** [jasonsturges/babylonjs-sveltekit#4]
[babylonjs-sveltekit](https://github.com/jasonsturges/babylonjs-sveltekit/tree/main)/[src](https://github.com/jasonsturges/babylonjs-sveltekit/tree/main/src)/[lib](https://github.com/jasonsturges/babylonjs-sveltekit/tree/main/src/lib)
/scene.js

Can it be TS? Seems poor form to mix the two.

**Comment by jasonsturges** [comment]
Pretty simple change, but committed if you need help.
